sudo: false
language: node_js
node_js:
  - "4.1"
cache:
  directories:
  - node_modules
branches:
  only:
  - master
env:
  - PHANTOMJS_DOWNLOADURL=https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
