sudo: required
language: node_js
node_js:
  - "4.1"
before_install:
  - sudo rm -rf /usr/local/phantomjs
  - npm set progress=false
  - npm install
cache:
  directories:
  - node_modules
branches:
  only:
  - master
env:
  - PHANTOMJS_DOWNLOADURL=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
