sudo: required
language: node_js
node_js:
  - stable
before_install:
  - sudo apt-get install libicu52
  - export PATH=$PWD/node_modules/.bin:$PATH
  - npm set progress=false
  - mkdir travis
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis/phantomjs2.tar.bz2
  - tar -xvf $PWD/travis/phantomjs2.tar.bz2 -C $PWD/travis/
  - ls -al $PWD/travis/
  - export PATH=$PWD/travis/phantomjs-2.1.1-linux-x86_64/bin/:$PATH
cache:
  directories:
    - node_modules
branches:
  only:
    - master
env:
  - PHANTOMJS_DOWNLOADURL=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
